language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Te/bqhL9VUR88+Lz0oBTXgBrqq5jOEwissarT6Ya5ZDPOrjhTDnxMNoUxi8I2LKddlqgcsD94N0hMH32lwCAbYTAZfB+8aHks5q2XZ+DJN8ClBKO1wTk4G4TKeRHWwNNLZXa4xTsJxpFcTCl5v4YdYU7ow3HI33GDKukAK2AQvl7NOFqjKuFWSzodSiWkpReuxBy248vS6wUEBQQYGydeZw5XXc+A32ZJoQC5txpSTh0xNuIr7yVDkO7NViWJ7wdpVRBzaBGAjDaVbm7DSZFFNNhCID2agOWqRef25XT0QIGNSpwtx5WrYf/2AEVf7SNe6DYrfLjSuoyDsr39melcZSZYTRAgTl0fS2Cv3omtjoM854yqbIaTRD0VlMpouFvhvGEFxhPfxAZaD1rOjw/vNiUUgouRPQhDQK6CCXYDxYboSK5wf0A7gqzgpFjKQRe6RZEBx9PrX/bbN9GjeKgQp6aYAgRqemUMWDsSNXtt/1PHTSSawSjh1VvPnrvnAO2DlDDwpzPNbWHaA6or+nbekDHrHgQFqpjnlbIsTx7U2oRakPh9ntjvvesS1RPQrX63smZUMHQ23zObd52OhIeQ92XmAISV2nPjTo5kzv4gy6vkIQpBYpmiQyzdLjoNa4WKdBgcUho3HCckSocmxStsE79xfvlbJ5YMmYhy9bvrCw=
  app: ReligiousTolerancePledge
  on:
    repo: ladyjem/ReligiousTolerancePledge
